# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(552, 186)
        Dialog.setStyleSheet("background-color: rgb(45, 55, 66);")
        self.centralwidget = QtWidgets.QWidget(Dialog)
        self.centralwidget.setObjectName("centralwidget")
        self.DialogClose = QtWidgets.QPushButton(self.centralwidget)
        
        # Cerrando dialog
        self.DialogClose.clicked.connect(lambda:Dialog.close())
        
        self.DialogClose.setGeometry(QtCore.QRect(203, 130, 131, 34))
        self.DialogClose.setStyleSheet("color: rgb(230, 220, 190);\n"
"font: 57 14pt \"Bedstead\";\n"
"")
        self.DialogClose.setObjectName("DialogClose")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 20, 81, 31))
        self.label.setStyleSheet("font: 57 20pt \"Bedstead\";\n"
"color: rgb(230, 220, 190);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 80, 351, 18))
        self.label_2.setStyleSheet("margin:auto;\n"
"font: 57 12pt \"Bedstead\";\n"
"color: rgb(0, 193, 228);")
        self.label_2.setObjectName("label_2")
        Dialog.setCentralWidget(self.centralwidget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "MainWindow"))
        self.DialogClose.setText(_translate("Dialog", "Close"))
        self.label.setText(_translate("Dialog", "Error"))
        self.label_2.setText(_translate("Dialog", "Need video url from youtube"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QMainWindow()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
